# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ "opened", "synchronize", "edited" ]

permissions:
  contents: read

jobs:
  test:
    name: 'Build and Test Library'
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        dc: [ldc-beta, ldc-1.41.0, dmd]
        exclude:
          - os: macOS-latest
            dc: dmd

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Install compiler
      uses: dlang-community/setup-dlang@v2
      with:
        compiler: ${{ matrix.dc }}

    - name: 'Build with ${{ matrix.os }} ${{ matrix.dc }}' 
      run: |
        # Build and run tests, as defined by `unittest` configuration
        # In this mode, `mainSourceFile` is excluded and `version (unittest)` are included
        # See https://dub.pm/package-format-json.html#configurations
        dub test --config=unittest
        dub run -y redub -- test

        # Ditto, in release mode.
        # Sometimes D packages break in release mode, so this is important to test.
        dub test --config=unittest --build=release
        dub run -y redub -- test --build=release

  test_build:
    name: 'Do buildchecks'
    strategy:
      matrix:
        to_build:
          - repo: Inochi2D/hairetsu
            tag: main
            config: unittest
            version: "99.0.0"
            may_fail: false
            linux_deps: "libfontconfig-dev"
            run_tests: true
    
    needs: test
    uses: ./.github/workflows/dub_test_build.yml
    with:
      repo: ${{ matrix.to_build.repo }}
      repo_tag: ${{ matrix.to_build.tag }}
      dep_config: ${{ matrix.to_build.config }}
      dep_version: ${{ matrix.to_build.version }}
      may_fail: ${{ matrix.to_build.may_fail }}
      linux_deps: ${{ matrix.to_build.linux_deps }}
      osx_deps: ${{ matrix.to_build.osx_deps }}
      run_tests: ${{ matrix.to_build.run_tests }}